messages_failure = {
    'invalid_information' : 'Invalid username or password!',
    'username_existed' : 'Username {0} is already existed!',
    'email_existed' : 'Email {0} is already used!',
    'phone_existed' : 'Phone {0} is already used!',
    'password_not_matched' : 'Password is not match!',
    'invalid_email' : 'Email {0} is invalid!',
    'invalid_password' : 'Your password does not match our records!',
    'token_expired' : 'The link has been expired!',
    'document_not_found' : 'No document matching the filter criteria!',
    'login_failure' : 'Login failed!',
    'null_data': '{0} can not null',
    'send_otp_failure': "OTP hasn't send to your email!",
    'OTP_invalid': 'OTP code is invalid!',
    'account_not_found': 'Account does not exist!',
    'internal_server_error': 'Internal Server Error!',
    'balance_not_enough': 'Balance is not enough to {0}!',
    'must_input_value': 'Please fill in all information!',
    'investment_not_exist': 'Investment does not exist!',
}

messages_success = {
    'create_success': '{0} is created successfully',
    'link_sent' : 'A reset password link is sent to {0}',
    'update_success' : 'You have successfully update your {0}',
    'register_success' : 'Successfully registered',
    'login_success' : 'You have login successfully!',
    'register_success' : 'Account have been successfully created',
    'delete_success' : '{0} deleted successfully',
    'send_otp_success': 'OTP has been sent to the email {0}!',
    'transfer_money_success': 'Transfer money successfully!',
    'payment_bill_success': 'Payment is processed successfully!',
    'investment_savings_created_success': 'Investment/Savings is created successfully!',
    'withdraw_cancel_success': '{0} investment successfully!',
    'locking_card_success': 'Your card is locked successfully!',
    'unlocking_card_success': 'Your card is unlocked successfully! '
}
